spring:
  application:
    name: notification-service
  kafka:
    auto-offset-reset: latest
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    group-id: ${KAFKA_GROUP_ID}
    topic:
      name: ${KAFKA_TOPIC}
  mail:
    host: ${MAIL_SERVER_HOST}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080