spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

server:
  port: ${GATEWAY_SERVICE_PORT}

jwt:
  secret:  ${JWT_SECRET}
