spring:
    application:
        name: doctor-service

    data:
        mongodb:
            uri: ${MONGO_URI}

logging:
    level:
        org:
            springframework:
                web: DEBUG
                servlet: DEBUG

server:
    port: ${DOCTOR_SERVICE_PORT}
