spring:
  application:
    name: doctor-service

  data:
    mongodb:
      uri: mongodb+srv://tempuser:tempuser@cluster0.yuuhwqt.mongodb.net/healthcare


logging:
  level:
    org:
      springframework:
        web: DEBUG
        servlet: DEBUG