app:
    environment: prod

spring:
    application:
        name: appointment-service

    data:
        mongodb:
            uri: ${MONGO_URI}

    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
        producer:
            topic: ${KAFKA_TOPIC}

logging:
    level:
        org:
            springframework:
                web: DEBUG
                servlet: DEBUG
            apache:
                kafka:
                    clients:
                        producer: DEBUG

server:
    port: ${APPOINTMENT_SERVICE_PORT:8080}

doctor:
    service:
        url: http://doctor-service:8080/api/v1/doctor

patient:
    service:
        url: http://patient-service:8080/api/v1/patient
    data:
        mongodb:
            uri: ${MONGO_URI}

